version: '3'
services:
  app:
    image: virtualwolf/papirus-image-generator:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./config.json:/opt/service/config.json
