version: '3.3'
services:
  generator:
    image: virtualwolf/papirus-image-generator:latest
    ports:
      - ${PORT}:3000
    restart: unless-stopped
    volumes:
      - ./config.json:/opt/service/config.json

